-- This line is to make sure that the consumers of this schema, for example
-- `scripts/test-schema.sh`, does not get confused about the lack of PostGIS
-- extension that we create in `scripts/init-db.sh`.
CREATE EXTENSION IF NOT EXISTS postgis;
CREATE EXTENSION IF NOT EXISTS pg_trgm;

CREATE SCHEMA IF NOT EXISTS socialmaps AUTHORIZATION socialmaps_api;

CREATE FUNCTION socialmaps.enforce_immutability()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    RAISE EXCEPTION 'cannot update immutable column(s)';
    RETURN NEW;
END;
$$;

CREATE TABLE socialmaps."user" (
    -- same as their OpenStreetMap ID
    id BIGINT PRIMARY KEY,
    created TIMESTAMP WITH TIME ZONE NOT NULL,
    updated TIMESTAMP WITH TIME ZONE NOT NULL,
    display_name TEXT NOT NULL
);

CREATE TRIGGER on_update_of_immutables_on_user
BEFORE UPDATE OF created ON socialmaps."user"
EXECUTE FUNCTION socialmaps.enforce_immutability();


CREATE TABLE socialmaps.place (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created TIMESTAMP WITH TIME ZONE NOT NULL,
    updated TIMESTAMP WITH TIME ZONE NOT NULL,
    "name" TEXT NOT NULL,
    "location" "public".GEOMETRY (POINT, 4326) NOT NULL,
    lat DOUBLE PRECISION NOT NULL GENERATED ALWAYS AS (ST_Y("location")) STORED,
    lon DOUBLE PRECISION NOT NULL GENERATED ALWAYS AS (ST_X("location")) STORED,
    osm_type CHARACTER(1) NOT NULL,
    osm_id BIGINT NOT NULL,

    CONSTRAINT "name" CHECK (LENGTH("name") <= 256),
    CONSTRAINT osm_type CHECK (osm_type IN ('N', 'W', 'R')),
    CONSTRAINT osm_id CHECK (osm_id >= 0)
);

CREATE INDEX place_location ON socialmaps.place USING gist ("location");

CREATE TRIGGER on_update_of_immutables_on_place
BEFORE UPDATE OF created ON socialmaps.place
EXECUTE FUNCTION socialmaps.enforce_immutability();

CREATE TABLE socialmaps.review (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created TIMESTAMP WITH TIME ZONE NOT NULL,
    updated TIMESTAMP WITH TIME ZONE NOT NULL,
    place_id BIGINT NOT NULL REFERENCES socialmaps.place (id),
    user_id BIGINT NOT NULL REFERENCES socialmaps."user" (id),
    -- `reviewed_at` is when the reviewed the Place.
    --
    -- `created` and `reviewed_at` values be different for reviews that are
    -- imported from other platforms, as those would be written long before
    -- they are added into Social Maps.
    reviewed_at TIMESTAMP WITH TIME ZONE NOT NULL,
    rating INTEGER NOT NULL,
    "comment" TEXT,

    last_decision_at TIMESTAMP WITH TIME ZONE,
    last_decision_by TEXT,
    last_decision_approved BOOLEAN,

    CONSTRAINT rating CHECK (
        rating BETWEEN 1 AND 5
    ),
    CONSTRAINT last_decision_approved CHECK (
        last_decision_approved IN (TRUE, FALSE)
    )
);

CREATE INDEX review_latest_by_place
ON socialmaps.review (
    place_id,
    last_decision_approved,
    created DESC
);

CREATE TRIGGER on_update_of_immutables_on_review
BEFORE UPDATE OF created, place_id, user_id ON socialmaps.review
EXECUTE FUNCTION socialmaps.enforce_immutability();

CREATE FUNCTION socialmaps.clear_last_decision_on_review_on_update_of_comment()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    IF OLD.comment <> NEW.comment THEN
        NEW.last_decision_at := NULL;
        NEW.last_decision_by := NULL;
        NEW.last_decision_approved := NULL;
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER on_update_of_comment_on_review
BEFORE UPDATE OF "comment" ON socialmaps.review
FOR EACH ROW
EXECUTE FUNCTION socialmaps.clear_last_decision_on_review_on_update_of_comment();

CREATE TABLE socialmaps.review_decision (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created TIMESTAMP WITH TIME ZONE NOT NULL,
    review_id BIGINT NOT NULL REFERENCES socialmaps.review (id),
    moderator TEXT NOT NULL,
    approved BOOLEAN NOT NULL,
    details TEXT NOT NULL,

    CONSTRAINT approved CHECK (approved IN (TRUE, FALSE))
);

CREATE FUNCTION socialmaps.update_review_on_new_review_decision()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    UPDATE socialmaps.review
    SET
        last_decision_at = NEW.created,
        last_decision_by = NEW.moderator,
        last_decision_approved = NEW.approved
    WHERE
        id = NEW.review_id
    ;
    RETURN NEW;
END;
$$;

CREATE TRIGGER on_insert_on_review_decision
AFTER INSERT ON socialmaps.review_decision
FOR EACH ROW
EXECUTE FUNCTION socialmaps.update_review_on_new_review_decision();

-- "review_decision" is immutable object.
CREATE TRIGGER on_update_on_review_decision
BEFORE UPDATE ON socialmaps.review_decision
EXECUTE FUNCTION socialmaps.enforce_immutability();

CREATE VIEW socialmaps.computed_place AS (
    SELECT
        place.*,
        COUNT(review.id) AS n_reviews,
        AVG(review.rating) AS avg_rating
    FROM socialmaps.place
    LEFT OUTER JOIN socialmaps.review ON place.id = review.place_id
    GROUP BY place.id
);

-- This is a workaround for sqlc to generate all-nilable fields for Place
-- in a LEFT OUTER JOIN.
-- See <https://github.com/sqlc-dev/sqlc/issues/2997#issuecomment-2667187835>
CREATE VIEW socialmaps.optional_computed_place AS (
    SELECT plc.*
    FROM
        ( -- noqa: ST11
            SELECT NULL
            WHERE
                FALSE
        ) AS "dummy"
    FULL JOIN socialmaps.computed_place AS plc ON TRUE
);
