-- This line is to make sure that the consumers of this schema, for example
-- `scripts/test-schema.sh`, does not get confused about the lack of PostGIS
-- extension that we create in `scripts/init-db.sh`.
CREATE EXTENSION IF NOT EXISTS postgis;

CREATE SCHEMA socialmaps AUTHORIZATION socialmaps_api;

CREATE FUNCTION socialmaps.enforce_immutability()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    RAISE EXCEPTION 'cannot update immutable column(s)';
    RETURN NEW;
END;
$$;

CREATE TABLE socialmaps."user" (
    -- same as their OpenStreetMap ID
    id BIGINT PRIMARY KEY,
    created TIMESTAMP WITH TIME ZONE NOT NULL,
    updated TIMESTAMP WITH TIME ZONE NOT NULL,
    display_name TEXT NOT NULL
);

CREATE TRIGGER on_update_of_immutables_on_user
BEFORE UPDATE OF created ON socialmaps."user"
EXECUTE FUNCTION socialmaps.enforce_immutability();


CREATE TABLE socialmaps.place (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created TIMESTAMP WITH TIME ZONE NOT NULL,
    updated TIMESTAMP WITH TIME ZONE NOT NULL,
    "name" TEXT NOT NULL,
    "location" "public".GEOMETRY (POINT, 4326) NOT NULL,
    lat DOUBLE PRECISION NOT NULL GENERATED ALWAYS AS (ST_Y("location")) STORED,
    lon DOUBLE PRECISION NOT NULL GENERATED ALWAYS AS (ST_X("location")) STORED,
    osm_type CHARACTER(1) NOT NULL,
    osm_id BIGINT NOT NULL,

    n_likes BIGINT NOT NULL DEFAULT 0,
    n_dislikes BIGINT NOT NULL DEFAULT 0,

    -- decayed number of likes
    dec_n_likes DOUBLE PRECISION NOT NULL DEFAULT 0,
    -- decayed number of dislikes
    dec_n_dislikes DOUBLE PRECISION NOT NULL DEFAULT 0,
    -- decayed numbers last updated (recalculated) at
    dec_updated_at TIMESTAMP WITH TIME ZONE NOT NULL,

    score DOUBLE PRECISION NOT NULL GENERATED ALWAYS AS (
        (dec_n_likes + 1.0) / ((dec_n_likes + 1.0) + (dec_n_dislikes + 1.0))
    ) STORED,

    CONSTRAINT "name" CHECK (LENGTH("name") <= 256),
    CONSTRAINT osm_type CHECK (osm_type IN ('N', 'W', 'R')),
    CONSTRAINT osm_id CHECK (osm_id >= 0),
    CONSTRAINT n_likes CHECK (n_likes >= 0),
    CONSTRAINT n_dislikes CHECK (n_dislikes >= 0),
    CONSTRAINT dec_n_likes CHECK (dec_n_likes BETWEEN 0 AND n_likes),
    CONSTRAINT dec_n_dislikes CHECK (
        dec_n_dislikes BETWEEN 0 AND n_dislikes
    )
);

-- This is a workaround for sqlc to generate all-nilable fields for Place
-- in a LEFT OUTER JOIN.
-- See <https://github.com/sqlc-dev/sqlc/issues/2997#issuecomment-2667187835>
CREATE VIEW socialmaps.place_view AS (
    SELECT plc.*
    FROM
        ( -- noqa: ST11
            SELECT NULL
            WHERE
                FALSE
        ) AS "dummy"
    FULL JOIN socialmaps.place AS plc ON TRUE
);

CREATE INDEX place_location ON socialmaps.place USING gist ("location");

CREATE TRIGGER on_update_of_immutables_on_place
BEFORE UPDATE OF created ON socialmaps.place
EXECUTE FUNCTION socialmaps.enforce_immutability();

CREATE FUNCTION socialmaps.decay_place_stats(
    place_id BIGINT,
    updating_at TIMESTAMP WITH TIME ZONE
)
RETURNS VOID
LANGUAGE plpgsql
AS $$
DECLARE
    dec_updated_at timestamp with time zone;
    factor double precision;
BEGIN
    SELECT place.dec_updated_at
    INTO dec_updated_at
    FROM socialmaps.place
    WHERE place.id = place_id
    FOR UPDATE;

    IF dec_updated_at > updating_at THEN
        RAISE EXCEPTION 'cannot decay: last update (dec_updated_at = %) was later (greater) than now (updating_at = %)', dec_updated_at, updating_at;
    END IF;

    factor := power(2, -(EXTRACT(EPOCH FROM (updating_at - dec_updated_at)) / 15552000.0));

    UPDATE socialmaps.place
    SET
        dec_n_likes    = dec_n_likes * factor,
        dec_n_dislikes = dec_n_dislikes * factor,
        dec_updated_at = updating_at
    WHERE
        id = place_id
    ;
END;
$$;

CREATE TABLE socialmaps.review (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created TIMESTAMP WITH TIME ZONE NOT NULL,
    updated TIMESTAMP WITH TIME ZONE NOT NULL,
    place_id BIGINT NOT NULL REFERENCES socialmaps.place (id),
    user_id BIGINT NOT NULL REFERENCES socialmaps."user" (id),
    liked BOOLEAN NOT NULL,
    "comment" TEXT,
    n_likes BIGINT NOT NULL DEFAULT 0,
    dec_n_likes DOUBLE PRECISION NOT NULL DEFAULT 0,
    -- decay updated (recalculated) at
    dec_updated_at TIMESTAMP WITH TIME ZONE NOT NULL,

    last_decision_at TIMESTAMP WITH TIME ZONE,
    last_decision_by TEXT,
    last_decision_approved BOOLEAN,

    CONSTRAINT liked CHECK (liked IN (TRUE, FALSE)),
    CONSTRAINT n_likes CHECK (n_likes >= 0),
    CONSTRAINT dec_n_likes CHECK (dec_n_likes >= 0),
    CONSTRAINT last_decision_approved CHECK (
        last_decision_approved IN (TRUE, FALSE)
    )
);

CREATE INDEX review_latest_by_place
ON socialmaps.review (
    place_id,
    last_decision_approved,
    created DESC
);

CREATE INDEX review_top_by_place
ON socialmaps.review (
    place_id,
    last_decision_approved,
    n_likes DESC,
    created DESC
);

CREATE INDEX review_hot_by_place
ON socialmaps.review (
    place_id,
    last_decision_approved,
    dec_n_likes DESC,
    created DESC
);

CREATE TRIGGER on_update_of_immutables_on_review
BEFORE UPDATE OF created, place_id, user_id ON socialmaps.review
EXECUTE FUNCTION socialmaps.enforce_immutability();


CREATE FUNCTION socialmaps.update_place_stats_on_change_on_review()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    IF TG_OP = 'DELETE' OR TG_OP = 'UPDATE' THEN
        IF OLD.liked THEN
            UPDATE socialmaps.place
            SET
                n_likes = n_likes - 1,
                dec_n_likes = dec_n_likes
                    - power(2, -(EXTRACT(EPOCH FROM (dec_updated_at - OLD.created)) / 15552000.0))
            WHERE
                place.id = OLD.place_id;
        ELSE
            UPDATE socialmaps.place
            SET
                n_dislikes = n_dislikes - 1,
                dec_n_dislikes = dec_n_dislikes
                    - power(2, -(EXTRACT(EPOCH FROM(dec_updated_at - OLD.created)) / 15552000.0))
            WHERE
                place.id = OLD.place_id;
        END IF;
    END IF;

    IF TG_OP = 'INSERT' OR TG_OP = 'UPDATE' THEN
        PERFORM socialmaps.decay_place_stats(NEW.place_id, NEW.updated);
        IF NEW.liked THEN
            UPDATE socialmaps.place
            SET
                n_likes = n_likes + 1,
                dec_n_likes = dec_n_likes + 1
            WHERE
                place.id = NEW.place_id;
        ELSE
            UPDATE socialmaps.place
            SET
                n_dislikes = n_dislikes + 1,
                dec_n_dislikes = dec_n_dislikes + 1
            WHERE
                place.id = NEW.place_id;
        END IF;
    END IF;

    IF TG_OP = 'DELETE' THEN
        RETURN OLD;
    ELSE
        RETURN NEW;
    END IF;
END;
$$;

CREATE TRIGGER on_insert_on_review
AFTER INSERT ON socialmaps.review
FOR EACH ROW
EXECUTE FUNCTION socialmaps.update_place_stats_on_change_on_review();

CREATE TRIGGER on_update_of_liked_on_review
AFTER UPDATE OF liked ON socialmaps.review
FOR EACH ROW
EXECUTE FUNCTION socialmaps.update_place_stats_on_change_on_review();

CREATE TRIGGER on_delete_on_review
AFTER DELETE ON socialmaps.review
FOR EACH ROW
EXECUTE FUNCTION socialmaps.update_place_stats_on_change_on_review();

CREATE FUNCTION socialmaps.clear_last_decision_on_review_on_update_of_comment()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    IF OLD.comment <> NEW.comment THEN
        NEW.last_decision_at := NULL;
        NEW.last_decision_by := NULL;
        NEW.last_decision_approved := NULL;
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER on_update_of_comment_on_review
BEFORE UPDATE OF "comment" ON socialmaps.review
FOR EACH ROW
EXECUTE FUNCTION socialmaps.clear_last_decision_on_review_on_update_of_comment();

CREATE TABLE socialmaps.review_decision (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created TIMESTAMP WITH TIME ZONE NOT NULL,
    review_id BIGINT NOT NULL REFERENCES socialmaps.review (id),
    moderator TEXT NOT NULL,
    approved BOOLEAN NOT NULL,
    details TEXT NOT NULL,

    CONSTRAINT approved CHECK (approved IN (TRUE, FALSE))
);

CREATE FUNCTION socialmaps.update_review_on_new_review_decision()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    UPDATE socialmaps.review
    SET
        last_decision_at = NEW.created,
        last_decision_by = NEW.moderator,
        last_decision_approved = NEW.approved
    WHERE
        id = NEW.review_id
    ;
    RETURN NEW;
END;
$$;

CREATE TRIGGER on_insert_on_review_decision
AFTER INSERT ON socialmaps.review_decision
FOR EACH ROW
EXECUTE FUNCTION socialmaps.update_review_on_new_review_decision();

-- "review_decision" is immutable object.
CREATE TRIGGER on_update_on_review_decision
BEFORE UPDATE ON socialmaps.review_decision
EXECUTE FUNCTION socialmaps.enforce_immutability();

CREATE TABLE socialmaps.review_like (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created TIMESTAMP WITH TIME ZONE NOT NULL,
    review_id BIGINT NOT NULL REFERENCES socialmaps.review (id),
    user_id BIGINT NOT NULL REFERENCES socialmaps."user" (id)
);

CREATE UNIQUE INDEX uniq_user_review_like ON socialmaps.review_like (
    review_id, user_id
);

-- "review_like" is an immutable object.
CREATE TRIGGER on_update_on_review_like
BEFORE UPDATE ON socialmaps.review_like
EXECUTE FUNCTION socialmaps.enforce_immutability();

CREATE FUNCTION socialmaps.update_review_on_new_review_like()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    UPDATE socialmaps.review
    SET
        n_likes
        = n_likes + 1,
        dec_n_likes
        = dec_n_likes * power(
            2,
            -(
                EXTRACT(EPOCH FROM (NEW.created - dec_updated_at))
                / 15552000.0
            )
        )
        + 1,
        dec_updated_at = NEW.created
    WHERE
        id = NEW.review_id
    ;
    RETURN NEW;
END;
$$;

CREATE TRIGGER on_insert_on_review_like
AFTER INSERT ON socialmaps.review_like
FOR EACH ROW
EXECUTE FUNCTION socialmaps.update_review_on_new_review_like();

CREATE FUNCTION socialmaps.on_review_like_delete_fn()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    UPDATE socialmaps.review
    SET
        n_likes = n_likes - 1,
        dec_n_likes
        = dec_n_likes - power(
            2,
            -(
                EXTRACT(EPOCH FROM (dec_updated_at - OLD.created))
                / 15552000.0
            )
        )
    WHERE
        id = OLD.review_id
    ;
    RETURN OLD;
END;
$$;

CREATE TRIGGER on_review_like_delete
AFTER DELETE ON socialmaps.review_like
FOR EACH ROW
EXECUTE FUNCTION socialmaps.on_review_like_delete_fn();
