on: [push]
jobs:
  test:
    runs-on: codeberg-small
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Set up Go
        uses: https://github.com/actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: Set up Staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Check formatting
        run: ./scripts/check-format.sh

      - name: Check deadcode
        run: ./scripts/check-deadcode.sh

      - name: Lint
        run: ./scripts/lint.sh

      - name: Build
        run: make

      - name: Test
        run: go test ./...
