// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package model

import (
	"time"
)

type Element struct {
	OsmType  string
	OsmID    int64
	Location interface{}
	Tags     map[string]string
	Lon      float64
	Lat      float64
	Name     string
}

type OptionalPlace struct {
	ID           *int64
	Created      *time.Time
	Updated      *time.Time
	Name         *string
	Location     interface{}
	Lat          *float64
	Lon          *float64
	OsmType      *string
	OsmID        *int64
	NLikes       *int64
	NDislikes    *int64
	DecNLikes    *float64
	DecNDislikes *float64
	DecUpdatedAt *time.Time
	Score        *float64
}

type Osm2pgsqlOsm2pgsqlProperty struct {
	Property string
	Value    string
}

type Place struct {
	ID           int64
	Created      time.Time
	Updated      time.Time
	Name         string
	Location     interface{}
	Lat          float64
	Lon          float64
	OsmType      string
	OsmID        int64
	NLikes       int64
	NDislikes    int64
	DecNLikes    float64
	DecNDislikes float64
	DecUpdatedAt time.Time
	Score        float64
}

type Review struct {
	ID                   int64
	Created              time.Time
	Updated              time.Time
	PlaceID              int64
	UserID               int64
	ReviewedAt           time.Time
	Liked                bool
	Comment              *string
	NLikes               int64
	DecNLikes            float64
	DecUpdatedAt         time.Time
	LastDecisionAt       *time.Time
	LastDecisionBy       *string
	LastDecisionApproved *bool
}

type ReviewDecision struct {
	ID        int64
	Created   time.Time
	ReviewID  int64
	Moderator string
	Approved  bool
	Details   string
}

type ReviewLike struct {
	ID       int64
	Created  time.Time
	ReviewID int64
	UserID   int64
}

type User struct {
	ID          int64
	Created     time.Time
	Updated     time.Time
	DisplayName string
}
