// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package model

import (
	"time"
)

type ComputedPlace struct {
	ID        int64
	Created   time.Time
	Updated   time.Time
	Name      string
	Location  interface{}
	Lat       float64
	Lon       float64
	OsmType   string
	OsmID     int64
	NReviews  int64
	AvgRating *float64
}

type Element struct {
	OsmType  string
	OsmID    int64
	Location interface{}
	Tags     map[string]string
	Lon      float64
	Lat      float64
	Name     string
}

type OptionalComputedPlace struct {
	ID        *int64
	Created   *time.Time
	Updated   *time.Time
	Name      *string
	Location  interface{}
	Lat       *float64
	Lon       *float64
	OsmType   *string
	OsmID     *int64
	NReviews  *int64
	AvgRating *float64
}

type Osm2pgsqlOsm2pgsqlProperty struct {
	Property string
	Value    string
}

type Place struct {
	ID       int64
	Created  time.Time
	Updated  time.Time
	Name     string
	Location interface{}
	Lat      float64
	Lon      float64
	OsmType  string
	OsmID    int64
}

type Review struct {
	ID                   int64
	Created              time.Time
	Updated              time.Time
	PlaceID              int64
	UserID               int64
	ReviewedAt           time.Time
	Rating               int32
	Comment              *string
	LastDecisionAt       *time.Time
	LastDecisionBy       *string
	LastDecisionApproved *bool
}

type ReviewDecision struct {
	ID        int64
	Created   time.Time
	ReviewID  int64
	Moderator string
	Approved  bool
	Details   string
}

type User struct {
	ID          int64
	Created     time.Time
	Updated     time.Time
	DisplayName string
}
