// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package model

import (
	"database/sql"
)

type Place struct {
	ID           int64
	Created      int64
	Updated      int64
	Name         string
	Lat          float64
	Lon          float64
	OsmType      string
	OsmID        int64
	NLikes       int64
	NDislikes    int64
	DecNLikes    float64
	DecNDislikes float64
	DecUpdatedAt int64
	Score        float64
}

type Review struct {
	ID                   int64
	Created              int64
	Updated              int64
	PlaceID              int64
	UserID               int64
	Liked                bool
	Comment              sql.NullString
	NLikes               int64
	DecNLikes            float64
	DecUpdatedAt         int64
	LastDecisionAt       sql.NullInt64
	LastDecisionBy       sql.NullString
	LastDecisionApproved sql.NullBool
}

type ReviewDecision struct {
	ID        int64
	Created   int64
	ReviewID  int64
	Moderator string
	Approved  bool
	Details   string
}

type ReviewLike struct {
	ID       int64
	Created  int64
	ReviewID int64
	UserID   int64
}

type User struct {
	ID          int64
	Created     int64
	Updated     int64
	DisplayName string
}
