// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package model

import (
	"context"
	"database/sql"
)

const createPlace = `-- name: CreatePlace :one
INSERT INTO place (
    name,
    lat,
    lon,
    osm_type,
    osm_id
)
VALUES (
    ?,
    ?,
    ?,
    ?,
    ?
)
RETURNING id, created, updated, name, lat, lon, osm_type, osm_id, n_likes, n_dislikes, dec_n_likes, dec_n_dislikes, dec_updated_at, score
`

func (q *Queries) CreatePlace(ctx context.Context, name string, lat float64, lon float64, osmType string, osmID int64) (Place, error) {
	row := q.db.QueryRowContext(ctx, createPlace,
		name,
		lat,
		lon,
		osmType,
		osmID,
	)
	var i Place
	err := row.Scan(
		&i.ID,
		&i.Created,
		&i.Updated,
		&i.Name,
		&i.Lat,
		&i.Lon,
		&i.OsmType,
		&i.OsmID,
		&i.NLikes,
		&i.NDislikes,
		&i.DecNLikes,
		&i.DecNDislikes,
		&i.DecUpdatedAt,
		&i.Score,
	)
	return i, err
}

const createReview = `-- name: CreateReview :one
INSERT INTO review (
    place_id,
    user_id,
    liked,
    comment
)
VALUES (
    ?,
    ?,
    ?,
    ?
) RETURNING id, created, updated, place_id, user_id, liked, comment, n_likes, dec_n_likes, dec_updated_at, last_decision_at, last_decision_by, last_decision_approved
`

func (q *Queries) CreateReview(ctx context.Context, placeID int64, userID int64, liked bool, comment sql.NullString) (Review, error) {
	row := q.db.QueryRowContext(ctx, createReview,
		placeID,
		userID,
		liked,
		comment,
	)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.Created,
		&i.Updated,
		&i.PlaceID,
		&i.UserID,
		&i.Liked,
		&i.Comment,
		&i.NLikes,
		&i.DecNLikes,
		&i.DecUpdatedAt,
		&i.LastDecisionAt,
		&i.LastDecisionBy,
		&i.LastDecisionApproved,
	)
	return i, err
}

const createReviewDecision = `-- name: CreateReviewDecision :one
INSERT INTO review_decision (
    review_id,
    moderator,
    approved,
    details
) VALUES (
    ?,
    ?,
    ?,
    ?
) RETURNING id, created, review_id, moderator, approved, details
`

func (q *Queries) CreateReviewDecision(ctx context.Context, reviewID int64, moderator string, approved bool, details string) (ReviewDecision, error) {
	row := q.db.QueryRowContext(ctx, createReviewDecision,
		reviewID,
		moderator,
		approved,
		details,
	)
	var i ReviewDecision
	err := row.Scan(
		&i.ID,
		&i.Created,
		&i.ReviewID,
		&i.Moderator,
		&i.Approved,
		&i.Details,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO user (
    id,
    display_name
) VALUES (
    ?,
    ?
)
ON CONFLICT (id) DO UPDATE SET display_name = excluded.display_name
RETURNING id, created, updated, display_name
`

func (q *Queries) CreateUser(ctx context.Context, iD int64, displayName string) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, iD, displayName)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Created,
		&i.Updated,
		&i.DisplayName,
	)
	return i, err
}

const deleteReview = `-- name: DeleteReview :exec
DELETE FROM review
WHERE
    id = ?
`

func (q *Queries) DeleteReview(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteReview, id)
	return err
}

const likeReview = `-- name: LikeReview :exec
INSERT INTO review_like (
    review_id,
    user_id

) VALUES (
    ?,
    ?
)
ON CONFLICT DO NOTHING
`

func (q *Queries) LikeReview(ctx context.Context, reviewID int64, userID int64) error {
	_, err := q.db.ExecContext(ctx, likeReview, reviewID, userID)
	return err
}

const listEarliestUnapprovedReviews = `-- name: ListEarliestUnapprovedReviews :many
SELECT id, created, updated, place_id, user_id, liked, comment, n_likes, dec_n_likes, dec_updated_at, last_decision_at, last_decision_by, last_decision_approved
FROM review
WHERE
    last_decision_approved IS NULL
    AND created >= ?1
    AND id > ?2
ORDER BY
    created ASC,
    id ASC
LIMIT
    ?3
`

func (q *Queries) ListEarliestUnapprovedReviews(ctx context.Context, lastCreated int64, lastID int64, limit int64) ([]Review, error) {
	rows, err := q.db.QueryContext(ctx, listEarliestUnapprovedReviews, lastCreated, lastID, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Review
	for rows.Next() {
		var i Review
		if err := rows.Scan(
			&i.ID,
			&i.Created,
			&i.Updated,
			&i.PlaceID,
			&i.UserID,
			&i.Liked,
			&i.Comment,
			&i.NLikes,
			&i.DecNLikes,
			&i.DecUpdatedAt,
			&i.LastDecisionAt,
			&i.LastDecisionBy,
			&i.LastDecisionApproved,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHottestApprovedReviewsOfPlace = `-- name: ListHottestApprovedReviewsOfPlace :many
SELECT id, created, updated, place_id, user_id, liked, comment, n_likes, dec_n_likes, dec_updated_at, last_decision_at, last_decision_by, last_decision_approved
FROM review
WHERE
    place_id = ?
    AND last_decision_approved
    AND dec_n_likes <= ?
    AND id < ?
ORDER BY
    dec_n_likes DESC,
    id DESC
LIMIT
    ?
`

func (q *Queries) ListHottestApprovedReviewsOfPlace(ctx context.Context, placeID int64, lastDecNLikes float64, lastID int64, limit int64) ([]Review, error) {
	rows, err := q.db.QueryContext(ctx, listHottestApprovedReviewsOfPlace,
		placeID,
		lastDecNLikes,
		lastID,
		limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Review
	for rows.Next() {
		var i Review
		if err := rows.Scan(
			&i.ID,
			&i.Created,
			&i.Updated,
			&i.PlaceID,
			&i.UserID,
			&i.Liked,
			&i.Comment,
			&i.NLikes,
			&i.DecNLikes,
			&i.DecUpdatedAt,
			&i.LastDecisionAt,
			&i.LastDecisionBy,
			&i.LastDecisionApproved,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLatestApprovedReviewsOfPlace = `-- name: ListLatestApprovedReviewsOfPlace :many
SELECT id, created, updated, place_id, user_id, liked, comment, n_likes, dec_n_likes, dec_updated_at, last_decision_at, last_decision_by, last_decision_approved
FROM review
WHERE
    place_id = ?
    AND last_decision_approved
    AND created <= ?
    AND id < ?
ORDER BY
    created DESC,
    id DESC
LIMIT
    ?
`

func (q *Queries) ListLatestApprovedReviewsOfPlace(ctx context.Context, placeID int64, lastCreated int64, lastID int64, limit int64) ([]Review, error) {
	rows, err := q.db.QueryContext(ctx, listLatestApprovedReviewsOfPlace,
		placeID,
		lastCreated,
		lastID,
		limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Review
	for rows.Next() {
		var i Review
		if err := rows.Scan(
			&i.ID,
			&i.Created,
			&i.Updated,
			&i.PlaceID,
			&i.UserID,
			&i.Liked,
			&i.Comment,
			&i.NLikes,
			&i.DecNLikes,
			&i.DecUpdatedAt,
			&i.LastDecisionAt,
			&i.LastDecisionBy,
			&i.LastDecisionApproved,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLatestApprovedReviewsOfPlaceReverse = `-- name: ListLatestApprovedReviewsOfPlaceReverse :many
SELECT id, created, updated, place_id, user_id, liked, comment, n_likes, dec_n_likes, dec_updated_at, last_decision_at, last_decision_by, last_decision_approved
FROM review
WHERE
    place_id = ?
    AND last_decision_approved
    AND created >= ?
    AND id > ?
ORDER BY
    created DESC,
    id DESC
LIMIT
    ?
`

func (q *Queries) ListLatestApprovedReviewsOfPlaceReverse(ctx context.Context, placeID int64, firstCreated int64, firstID int64, limit int64) ([]Review, error) {
	rows, err := q.db.QueryContext(ctx, listLatestApprovedReviewsOfPlaceReverse,
		placeID,
		firstCreated,
		firstID,
		limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Review
	for rows.Next() {
		var i Review
		if err := rows.Scan(
			&i.ID,
			&i.Created,
			&i.Updated,
			&i.PlaceID,
			&i.UserID,
			&i.Liked,
			&i.Comment,
			&i.NLikes,
			&i.DecNLikes,
			&i.DecUpdatedAt,
			&i.LastDecisionAt,
			&i.LastDecisionBy,
			&i.LastDecisionApproved,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlacesByCoord = `-- name: ListPlacesByCoord :many
SELECT id, created, updated, name, lat, lon, osm_type, osm_id, n_likes, n_dislikes, dec_n_likes, dec_n_dislikes, dec_updated_at, score
FROM
    place
WHERE
    ?1 <= lat AND lat <= ?2
    AND ?3 <= lon AND lon <= ?4
`

func (q *Queries) ListPlacesByCoord(ctx context.Context, latMin float64, latMax float64, lonMin float64, lonMax float64) ([]Place, error) {
	rows, err := q.db.QueryContext(ctx, listPlacesByCoord,
		latMin,
		latMax,
		lonMin,
		lonMax,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Place
	for rows.Next() {
		var i Place
		if err := rows.Scan(
			&i.ID,
			&i.Created,
			&i.Updated,
			&i.Name,
			&i.Lat,
			&i.Lon,
			&i.OsmType,
			&i.OsmID,
			&i.NLikes,
			&i.NDislikes,
			&i.DecNLikes,
			&i.DecNDislikes,
			&i.DecUpdatedAt,
			&i.Score,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const loadLatestDecisionOfReview = `-- name: LoadLatestDecisionOfReview :one
SELECT id, created, review_id, moderator, approved, details
FROM review_decision
WHERE
    review_id = ?
ORDER BY
    created DESC
LIMIT 1
`

func (q *Queries) LoadLatestDecisionOfReview(ctx context.Context, reviewID int64) (ReviewDecision, error) {
	row := q.db.QueryRowContext(ctx, loadLatestDecisionOfReview, reviewID)
	var i ReviewDecision
	err := row.Scan(
		&i.ID,
		&i.Created,
		&i.ReviewID,
		&i.Moderator,
		&i.Approved,
		&i.Details,
	)
	return i, err
}

const loadPlace = `-- name: LoadPlace :one
SELECT id, created, updated, name, lat, lon, osm_type, osm_id, n_likes, n_dislikes, dec_n_likes, dec_n_dislikes, dec_updated_at, score
FROM
    place
WHERE
    id = ?
`

func (q *Queries) LoadPlace(ctx context.Context, id int64) (Place, error) {
	row := q.db.QueryRowContext(ctx, loadPlace, id)
	var i Place
	err := row.Scan(
		&i.ID,
		&i.Created,
		&i.Updated,
		&i.Name,
		&i.Lat,
		&i.Lon,
		&i.OsmType,
		&i.OsmID,
		&i.NLikes,
		&i.NDislikes,
		&i.DecNLikes,
		&i.DecNDislikes,
		&i.DecUpdatedAt,
		&i.Score,
	)
	return i, err
}

const loadReview = `-- name: LoadReview :one
SELECT id, created, updated, place_id, user_id, liked, comment, n_likes, dec_n_likes, dec_updated_at, last_decision_at, last_decision_by, last_decision_approved
FROM review
WHERE
    id = ?
`

func (q *Queries) LoadReview(ctx context.Context, id int64) (Review, error) {
	row := q.db.QueryRowContext(ctx, loadReview, id)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.Created,
		&i.Updated,
		&i.PlaceID,
		&i.UserID,
		&i.Liked,
		&i.Comment,
		&i.NLikes,
		&i.DecNLikes,
		&i.DecUpdatedAt,
		&i.LastDecisionAt,
		&i.LastDecisionBy,
		&i.LastDecisionApproved,
	)
	return i, err
}

const unlikeReview = `-- name: UnlikeReview :exec
DELETE FROM review_like
WHERE
    review_id = ?
    AND user_id = ?
`

func (q *Queries) UnlikeReview(ctx context.Context, reviewID int64, userID int64) error {
	_, err := q.db.ExecContext(ctx, unlikeReview, reviewID, userID)
	return err
}

const updateReview = `-- name: UpdateReview :one
UPDATE review SET
    liked = ?,
    comment = ?
WHERE
    id = ?
RETURNING id, created, updated, place_id, user_id, liked, comment, n_likes, dec_n_likes, dec_updated_at, last_decision_at, last_decision_by, last_decision_approved
`

func (q *Queries) UpdateReview(ctx context.Context, liked bool, comment sql.NullString, iD int64) (Review, error) {
	row := q.db.QueryRowContext(ctx, updateReview, liked, comment, iD)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.Created,
		&i.Updated,
		&i.PlaceID,
		&i.UserID,
		&i.Liked,
		&i.Comment,
		&i.NLikes,
		&i.DecNLikes,
		&i.DecUpdatedAt,
		&i.LastDecisionAt,
		&i.LastDecisionBy,
		&i.LastDecisionApproved,
	)
	return i, err
}
