// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package model

import (
	"context"
	"time"
)

const createPlace = `-- name: CreatePlace :one
INSERT INTO socialmaps.place (
    "name",
    "location",
    osm_type,
    osm_id,
    created,
    updated,
    dec_updated_at
)
VALUES (
    $1,
    ST_POINT($2::double precision, $3::double precision, 4326),
    $4,
    $5,
    $6,
    $6,
    $6
)
RETURNING id, created, updated, name, location, lat, lon, osm_type, osm_id, n_likes, n_dislikes, dec_n_likes, dec_n_dislikes, dec_updated_at, score
`

func (q *Queries) CreatePlace(ctx context.Context, name string, lon float64, lat float64, osmType string, osmID int64, asOf time.Time) (Place, error) {
	row := q.db.QueryRow(ctx, createPlace,
		name,
		lon,
		lat,
		osmType,
		osmID,
		asOf,
	)
	var i Place
	err := row.Scan(
		&i.ID,
		&i.Created,
		&i.Updated,
		&i.Name,
		&i.Location,
		&i.Lat,
		&i.Lon,
		&i.OsmType,
		&i.OsmID,
		&i.NLikes,
		&i.NDislikes,
		&i.DecNLikes,
		&i.DecNDislikes,
		&i.DecUpdatedAt,
		&i.Score,
	)
	return i, err
}

const createReview = `-- name: CreateReview :one
INSERT INTO socialmaps.review (
    place_id,
    user_id,
    liked,
    "comment",
    created,
    updated,
    dec_updated_at
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $5,
    $5
) RETURNING id, created, updated, place_id, user_id, liked, comment, n_likes, dec_n_likes, dec_updated_at, last_decision_at, last_decision_by, last_decision_approved
`

func (q *Queries) CreateReview(ctx context.Context, placeID int64, userID int64, liked bool, comment *string, asOf time.Time) (Review, error) {
	row := q.db.QueryRow(ctx, createReview,
		placeID,
		userID,
		liked,
		comment,
		asOf,
	)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.Created,
		&i.Updated,
		&i.PlaceID,
		&i.UserID,
		&i.Liked,
		&i.Comment,
		&i.NLikes,
		&i.DecNLikes,
		&i.DecUpdatedAt,
		&i.LastDecisionAt,
		&i.LastDecisionBy,
		&i.LastDecisionApproved,
	)
	return i, err
}

const createReviewDecision = `-- name: CreateReviewDecision :one
INSERT INTO socialmaps.review_decision (
    created,
    review_id,
    moderator,
    approved,
    details
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
) RETURNING id, created, review_id, moderator, approved, details
`

func (q *Queries) CreateReviewDecision(ctx context.Context, asOf time.Time, reviewID int64, moderator string, approved bool, details string) (ReviewDecision, error) {
	row := q.db.QueryRow(ctx, createReviewDecision,
		asOf,
		reviewID,
		moderator,
		approved,
		details,
	)
	var i ReviewDecision
	err := row.Scan(
		&i.ID,
		&i.Created,
		&i.ReviewID,
		&i.Moderator,
		&i.Approved,
		&i.Details,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO socialmaps."user" (
    created,
    updated,
    id,
    display_name
) VALUES (
    $1,
    $1,
    $2,
    $3
)
ON CONFLICT (id) DO UPDATE SET display_name = excluded.display_name
RETURNING id, created, updated, display_name
`

func (q *Queries) CreateUser(ctx context.Context, asOf time.Time, iD int64, displayName string) (User, error) {
	row := q.db.QueryRow(ctx, createUser, asOf, iD, displayName)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Created,
		&i.Updated,
		&i.DisplayName,
	)
	return i, err
}

const deleteReview = `-- name: DeleteReview :exec
DELETE FROM socialmaps.review
WHERE
    id = $1
`

func (q *Queries) DeleteReview(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteReview, id)
	return err
}

const likeReview = `-- name: LikeReview :exec
INSERT INTO socialmaps.review_like (
    review_id,
    user_id,
    created
) VALUES (
    $1,
    $2,
    $3
)
ON CONFLICT DO NOTHING
`

func (q *Queries) LikeReview(ctx context.Context, reviewID int64, userID int64, asOf time.Time) error {
	_, err := q.db.Exec(ctx, likeReview, reviewID, userID, asOf)
	return err
}

const listEarliestUnapprovedReviews = `-- name: ListEarliestUnapprovedReviews :many
SELECT id, created, updated, place_id, user_id, liked, comment, n_likes, dec_n_likes, dec_updated_at, last_decision_at, last_decision_by, last_decision_approved
FROM socialmaps.review
WHERE
    last_decision_approved IS NULL
    AND created >= $1
    AND id > $2
ORDER BY
    created ASC,
    id ASC
LIMIT
    $3
`

func (q *Queries) ListEarliestUnapprovedReviews(ctx context.Context, lastCreated time.Time, lastID int64, lim int32) ([]Review, error) {
	rows, err := q.db.Query(ctx, listEarliestUnapprovedReviews, lastCreated, lastID, lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Review
	for rows.Next() {
		var i Review
		if err := rows.Scan(
			&i.ID,
			&i.Created,
			&i.Updated,
			&i.PlaceID,
			&i.UserID,
			&i.Liked,
			&i.Comment,
			&i.NLikes,
			&i.DecNLikes,
			&i.DecUpdatedAt,
			&i.LastDecisionAt,
			&i.LastDecisionBy,
			&i.LastDecisionApproved,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHottestApprovedReviewsOfPlace = `-- name: ListHottestApprovedReviewsOfPlace :many
SELECT id, created, updated, place_id, user_id, liked, comment, n_likes, dec_n_likes, dec_updated_at, last_decision_at, last_decision_by, last_decision_approved
FROM socialmaps.review
WHERE
    place_id = $1
    AND last_decision_approved
    AND dec_n_likes <= $3
    AND id < $4
ORDER BY
    dec_n_likes DESC,
    id DESC
LIMIT
    $2
`

func (q *Queries) ListHottestApprovedReviewsOfPlace(ctx context.Context, placeID int64, limit int32, lastDecNLikes float64, lastID int64) ([]Review, error) {
	rows, err := q.db.Query(ctx, listHottestApprovedReviewsOfPlace,
		placeID,
		limit,
		lastDecNLikes,
		lastID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Review
	for rows.Next() {
		var i Review
		if err := rows.Scan(
			&i.ID,
			&i.Created,
			&i.Updated,
			&i.PlaceID,
			&i.UserID,
			&i.Liked,
			&i.Comment,
			&i.NLikes,
			&i.DecNLikes,
			&i.DecUpdatedAt,
			&i.LastDecisionAt,
			&i.LastDecisionBy,
			&i.LastDecisionApproved,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLatestApprovedReviewsOfPlace = `-- name: ListLatestApprovedReviewsOfPlace :many
SELECT
    rvw.id, rvw.created, rvw.updated, rvw.place_id, rvw.user_id, rvw.liked, rvw.comment, rvw.n_likes, rvw.dec_n_likes, rvw.dec_updated_at, rvw.last_decision_at, rvw.last_decision_by, rvw.last_decision_approved, -- noqa
    usr.id, usr.created, usr.updated, usr.display_name -- noqa
FROM socialmaps.review AS rvw
INNER JOIN socialmaps."user" AS usr ON rvw.user_id = usr.id
WHERE
    rvw.place_id = $1
    AND rvw.last_decision_approved
    AND rvw.created <= TO_TIMESTAMP($2)
    AND rvw.id < $3
ORDER BY
    rvw.created DESC,
    rvw.id DESC
LIMIT
    $4::bigint
`

type ListLatestApprovedReviewsOfPlaceRow struct {
	Review Review
	User   User
}

func (q *Queries) ListLatestApprovedReviewsOfPlace(ctx context.Context, placeID int64, lastCreated float64, lastID int64, lmt int64) ([]ListLatestApprovedReviewsOfPlaceRow, error) {
	rows, err := q.db.Query(ctx, listLatestApprovedReviewsOfPlace,
		placeID,
		lastCreated,
		lastID,
		lmt,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLatestApprovedReviewsOfPlaceRow
	for rows.Next() {
		var i ListLatestApprovedReviewsOfPlaceRow
		if err := rows.Scan(
			&i.Review.ID,
			&i.Review.Created,
			&i.Review.Updated,
			&i.Review.PlaceID,
			&i.Review.UserID,
			&i.Review.Liked,
			&i.Review.Comment,
			&i.Review.NLikes,
			&i.Review.DecNLikes,
			&i.Review.DecUpdatedAt,
			&i.Review.LastDecisionAt,
			&i.Review.LastDecisionBy,
			&i.Review.LastDecisionApproved,
			&i.User.ID,
			&i.User.Created,
			&i.User.Updated,
			&i.User.DisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLatestApprovedReviewsOfPlaceReverse = `-- name: ListLatestApprovedReviewsOfPlaceReverse :many
SELECT
    rvw.id, rvw.created, rvw.updated, rvw.place_id, rvw.user_id, rvw.liked, rvw.comment, rvw.n_likes, rvw.dec_n_likes, rvw.dec_updated_at, rvw.last_decision_at, rvw.last_decision_by, rvw.last_decision_approved, -- noqa
    usr.id, usr.created, usr.updated, usr.display_name -- noqa
FROM socialmaps.review AS rvw
INNER JOIN socialmaps."user" AS usr ON rvw.user_id = usr.id
WHERE
    rvw.place_id = $1
    AND rvw.last_decision_approved
    AND rvw.created >= TO_TIMESTAMP($2)
    AND rvw.id > $3
ORDER BY
    rvw.created DESC,
    rvw.id DESC
LIMIT
    $4::bigint
`

type ListLatestApprovedReviewsOfPlaceReverseRow struct {
	Review Review
	User   User
}

func (q *Queries) ListLatestApprovedReviewsOfPlaceReverse(ctx context.Context, placeID int64, firstCreated float64, firstID int64, lmt int64) ([]ListLatestApprovedReviewsOfPlaceReverseRow, error) {
	rows, err := q.db.Query(ctx, listLatestApprovedReviewsOfPlaceReverse,
		placeID,
		firstCreated,
		firstID,
		lmt,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLatestApprovedReviewsOfPlaceReverseRow
	for rows.Next() {
		var i ListLatestApprovedReviewsOfPlaceReverseRow
		if err := rows.Scan(
			&i.Review.ID,
			&i.Review.Created,
			&i.Review.Updated,
			&i.Review.PlaceID,
			&i.Review.UserID,
			&i.Review.Liked,
			&i.Review.Comment,
			&i.Review.NLikes,
			&i.Review.DecNLikes,
			&i.Review.DecUpdatedAt,
			&i.Review.LastDecisionAt,
			&i.Review.LastDecisionBy,
			&i.Review.LastDecisionApproved,
			&i.User.ID,
			&i.User.Created,
			&i.User.Updated,
			&i.User.DisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const loadLatestDecisionOfReview = `-- name: LoadLatestDecisionOfReview :one
SELECT id, created, review_id, moderator, approved, details
FROM socialmaps.review_decision
WHERE
    review_id = $1
ORDER BY
    created DESC
LIMIT 1
`

func (q *Queries) LoadLatestDecisionOfReview(ctx context.Context, reviewID int64) (ReviewDecision, error) {
	row := q.db.QueryRow(ctx, loadLatestDecisionOfReview, reviewID)
	var i ReviewDecision
	err := row.Scan(
		&i.ID,
		&i.Created,
		&i.ReviewID,
		&i.Moderator,
		&i.Approved,
		&i.Details,
	)
	return i, err
}

const loadPlace = `-- name: LoadPlace :one

SELECT
    elm.osm_type, elm.osm_id, elm.location, elm.tags, elm.lon, elm.lat, elm.name,  -- noqa
    plc.id, plc.created, plc.updated, plc.name, plc.location, plc.lat, plc.lon, plc.osm_type, plc.osm_id, plc.n_likes, plc.n_dislikes, plc.dec_n_likes, plc.dec_n_dislikes, plc.dec_updated_at, plc.score  -- noqa
FROM
    socialmaps.place AS plc
INNER JOIN osm2pgsql.element AS elm
    ON (
        ST_DWITHIN(plc."location"::geography, elm."location"::geography, 10)
        AND plc."name" = elm."name"
    )
WHERE
    plc.id = $1
`

type LoadPlaceRow struct {
	Element Element
	Place   Place
}

// TODO: we'll add order by later
func (q *Queries) LoadPlace(ctx context.Context, id int64) (LoadPlaceRow, error) {
	row := q.db.QueryRow(ctx, loadPlace, id)
	var i LoadPlaceRow
	err := row.Scan(
		&i.Element.OsmType,
		&i.Element.OsmID,
		&i.Element.Location,
		&i.Element.Tags,
		&i.Element.Lon,
		&i.Element.Lat,
		&i.Element.Name,
		&i.Place.ID,
		&i.Place.Created,
		&i.Place.Updated,
		&i.Place.Name,
		&i.Place.Location,
		&i.Place.Lat,
		&i.Place.Lon,
		&i.Place.OsmType,
		&i.Place.OsmID,
		&i.Place.NLikes,
		&i.Place.NDislikes,
		&i.Place.DecNLikes,
		&i.Place.DecNDislikes,
		&i.Place.DecUpdatedAt,
		&i.Place.Score,
	)
	return i, err
}

const loadReview = `-- name: LoadReview :one
SELECT id, created, updated, place_id, user_id, liked, comment, n_likes, dec_n_likes, dec_updated_at, last_decision_at, last_decision_by, last_decision_approved
FROM socialmaps.review
WHERE
    id = $1
`

func (q *Queries) LoadReview(ctx context.Context, id int64) (Review, error) {
	row := q.db.QueryRow(ctx, loadReview, id)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.Created,
		&i.Updated,
		&i.PlaceID,
		&i.UserID,
		&i.Liked,
		&i.Comment,
		&i.NLikes,
		&i.DecNLikes,
		&i.DecUpdatedAt,
		&i.LastDecisionAt,
		&i.LastDecisionBy,
		&i.LastDecisionApproved,
	)
	return i, err
}

const queryPlaces = `-- name: QueryPlaces :many
SELECT DISTINCT ON (elm."name") -- TODO: buggy. we want to allow same named POIs if they are apart enough
    elm.osm_type, elm.osm_id, elm.location, elm.tags, elm.lon, elm.lat, elm.name,  -- noqa
    plc.id, plc.created, plc.updated, plc.name, plc.location, plc.lat, plc.lon, plc.osm_type, plc.osm_id, plc.n_likes, plc.n_dislikes, plc.dec_n_likes, plc.dec_n_dislikes, plc.dec_updated_at, plc.score  -- noqa
FROM
    osm2pgsql.element AS elm
LEFT OUTER JOIN socialmaps.place_view AS plc
    ON (
        ST_DWITHIN(plc."location"::geography, elm."location"::geography, 10)
        AND elm."name" = plc."name"
        AND plc."location" && ST_MAKEENVELOPE(
            $1::double precision,
            $2::double precision,
            $3::double precision,
            $4::double precision,
            4326
        )
    )
WHERE
    elm."location" && ST_MAKEENVELOPE(
        $1::double precision,
        $2::double precision,
        $3::double precision,
        $4::double precision,
        4326
    )
    AND elm.tags @@ $5::jsonpath
LIMIT -- noqa: AM09
    100
`

type QueryPlacesRow struct {
	Element       Element
	OptionalPlace OptionalPlace
}

func (q *Queries) QueryPlaces(ctx context.Context, lonMin float64, latMin float64, lonMax float64, latMax float64, predicate interface{}) ([]QueryPlacesRow, error) {
	rows, err := q.db.Query(ctx, queryPlaces,
		lonMin,
		latMin,
		lonMax,
		latMax,
		predicate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QueryPlacesRow
	for rows.Next() {
		var i QueryPlacesRow
		if err := rows.Scan(
			&i.Element.OsmType,
			&i.Element.OsmID,
			&i.Element.Location,
			&i.Element.Tags,
			&i.Element.Lon,
			&i.Element.Lat,
			&i.Element.Name,
			&i.OptionalPlace.ID,
			&i.OptionalPlace.Created,
			&i.OptionalPlace.Updated,
			&i.OptionalPlace.Name,
			&i.OptionalPlace.Location,
			&i.OptionalPlace.Lat,
			&i.OptionalPlace.Lon,
			&i.OptionalPlace.OsmType,
			&i.OptionalPlace.OsmID,
			&i.OptionalPlace.NLikes,
			&i.OptionalPlace.NDislikes,
			&i.OptionalPlace.DecNLikes,
			&i.OptionalPlace.DecNDislikes,
			&i.OptionalPlace.DecUpdatedAt,
			&i.OptionalPlace.Score,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unlikeReview = `-- name: UnlikeReview :exec
DELETE FROM socialmaps.review_like
WHERE
    review_id = $1
    AND user_id = $2
`

func (q *Queries) UnlikeReview(ctx context.Context, reviewID int64, userID int64) error {
	_, err := q.db.Exec(ctx, unlikeReview, reviewID, userID)
	return err
}

const updateReview = `-- name: UpdateReview :one
UPDATE socialmaps.review SET
    liked = $1,
    "comment" = $2,
    updated = $4
WHERE
    id = $3
RETURNING id, created, updated, place_id, user_id, liked, comment, n_likes, dec_n_likes, dec_updated_at, last_decision_at, last_decision_by, last_decision_approved
`

func (q *Queries) UpdateReview(ctx context.Context, liked bool, comment *string, iD int64, asOf time.Time) (Review, error) {
	row := q.db.QueryRow(ctx, updateReview,
		liked,
		comment,
		iD,
		asOf,
	)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.Created,
		&i.Updated,
		&i.PlaceID,
		&i.UserID,
		&i.Liked,
		&i.Comment,
		&i.NLikes,
		&i.DecNLikes,
		&i.DecUpdatedAt,
		&i.LastDecisionAt,
		&i.LastDecisionBy,
		&i.LastDecisionApproved,
	)
	return i, err
}
